// Vocabulary behind utils/exerciseSearch.ts: the other names people give
// exercises, in English (gym nicknames, abbreviations) and French. French
// terms follow the names used by Strength Level's French exercise database
// (strengthlevel.fr), Decathlon's musculation glossary and common gym usage
// in France and Québec.
//
// Three layers, from broadest to most specific:
//   PHRASE_SYNONYMS  whole French expressions → the catalog's English words
//   WORD_SYNONYMS    single words (French, abbreviations, plurals) → English
//   ALIAS_RULES      nicknames that don't translate word for word
//
// All keys are in normalized form: lowercase, no accents, punctuation and
// hyphens turned into spaces (see normalizeSearchText).

// Words ignored in a query (unless it's made of nothing else).
export const STOPWORDS = new Set([
  "de", "du", "des", "d", "la", "le", "les", "l", "a", "au", "aux", "avec",
  "en", "sur", "et", "un", "une", "pour", "par",
  "the", "with", "on", "to", "and", "of", "an", "in", "for",
]);

// Multi-word French expressions, rewritten into the catalog's English
// before matching (the original query is matched too).
export const PHRASE_SYNONYMS: Record<string, string> = {
  // Big lifts
  "developpe couche": "bench press",
  "developpe couche prise serree": "close grip bench press",
  "developpe incline": "incline press",
  "developpe decline": "decline press",
  "developpe militaire": "overhead press",
  "developpe epaules": "shoulder press",
  "developpe nuque": "behind neck press",
  "developpe assis": "seated press",
  "developpe arnold": "arnold press",
  "presse a epaules": "shoulder press",
  "presse militaire": "military press",
  "presse pectorale": "chest press",
  "presse en poussee": "push press",
  "souleve de terre": "deadlift",
  "souleve de terre roumain": "romanian deadlift",
  "souleve de terre jambes tendues": "stiff leg deadlift",
  "souleve de terre sumo": "sumo deadlift",
  "barre hexagonale": "trap bar",
  "squat avant": "front squat",
  "squat arriere": "back squat",
  "squat bulgare": "split squat",
  "squat hackenberg": "hack squat",
  "squat gobelet": "goblet squat",
  "squat saute": "jump squat",
  "squat poids du corps": "bodyweight squat",
  // Back
  "tirage vertical": "lat pulldown",
  "tirage poitrine": "lat pulldown",
  "tirage nuque": "behind neck pulldown",
  "tirage horizontal": "seated cable row",
  "tirage assis": "seated row",
  "tirage poulie basse": "seated cable row",
  "tirage poulie haute": "lat pulldown",
  "tirage menton": "upright row",
  "tirage visage": "face pull",
  "rowing penche": "bent over row",
  "rowing barre": "barbell row",
  "rowing haltere": "dumbbell row",
  "rowing assis": "seated row",
  "rowing menton": "upright row",
  "rowing t": "t bar row",
  "traction supination": "chin up",
  "tractions supination": "chin up",
  "traction pronation": "pull up",
  "tractions pronation": "pull up",
  "traction prise neutre": "neutral grip pull up",
  "extension lombaire": "back extension",
  "chaise romaine": "captains chair",
  // Shoulders / traps
  "elevation laterale": "lateral raise",
  "elevations laterales": "lateral raise",
  "elevation frontale": "front raise",
  "elevations frontales": "front raise",
  "haussement d epaules": "shrug",
  "haussements d epaules": "shrug",
  "rotation externe": "external rotation",
  "rotation interne": "internal rotation",
  // Arms
  "curl biceps": "biceps curl",
  "curl marteau": "hammer curl",
  "curl pupitre": "preacher curl",
  "curl au pupitre": "preacher curl",
  "curl concentre": "concentration curl",
  "curl inverse": "reverse curl",
  "curl poignet": "wrist curl",
  "curl barre ez": "ez bar curl",
  "barre ez": "ez bar",
  "extension triceps": "triceps extension",
  "extension des triceps": "triceps extension",
  "extension triceps poulie": "triceps pushdown",
  "extension triceps nuque": "overhead triceps extension",
  "extension triceps allonge": "lying triceps extension",
  "barre au front": "skull crusher",
  "pompes diamant": "diamond push up",
  // Legs
  "presse a cuisses": "leg press",
  "presse cuisses": "leg press",
  "presse jambes": "leg press",
  "extension des jambes": "leg extension",
  "extension jambes": "leg extension",
  "curl jambes": "leg curl",
  "curl jambes assis": "seated leg curl",
  "curl jambes allonge": "lying leg curl",
  "curl ischios": "leg curl",
  "lever de mollets": "calf raise",
  "levee de mollets": "calf raise",
  "extension mollets": "calf raise",
  "poussee des hanches": "hip thrust",
  "pont fessier": "glute bridge",
  "releve de bassin": "glute bridge",
  "fente bulgare": "split squat",
  "fente arriere": "reverse lunge",
  "fente avant": "forward lunge",
  "fente laterale": "lateral lunge",
  "fentes marchees": "walking lunge",
  "montee sur banc": "step up",
  "chaise contre le mur": "wall sit",
  // Core
  "releve de buste": "sit up",
  "releve de jambes": "leg raise",
  "releve de genoux": "knee raise",
  "rotation russe": "russian twist",
  "roue abdominale": "ab wheel rollout",
  "grimpeur": "mountain climber",
  "grimpeurs": "mountain climber",
  // Cardio / misc
  "corde a sauter": "jump rope",
  "montee de genoux": "high knee",
  "montees de genoux": "high knee",
  "talons fesses": "butt kick",
  "marche du fermier": "farmer walk",
  "velo elliptique": "elliptical",
  "tapis de course": "treadmill",
  // Positions / equipment
  "au dessus de la tete": "overhead",
  "derriere la tete": "behind head",
  "a quatre pattes": "all fours",
  "quatre pattes": "all fours",
  "en appui": "supported",
  "avec appui": "supported",
  "poids du corps": "bodyweight",
  "prise serree": "close grip",
  "prise large": "wide grip",
  "prise neutre": "neutral grip",
  "prise inversee": "reverse grip",
  "un bras": "single arm",
  "une jambe": "single leg",
  "a genoux": "kneeling",
  "sur le dos": "supine",
  "a plat ventre": "prone",
  "ballon suisse": "stability ball",
  "swiss ball": "stability ball",
  "medecine ball": "medicine ball",
  "medicine ball": "medicine ball",
  "machine smith": "smith machine",
  "cadre guide": "smith machine",
  "barre guidee": "smith machine",
  "rouleau de massage": "foam roller",
  "rouleau mousse": "foam roller",
};

// Single query words → the catalog's English word(s). Covers the whole
// vocabulary of the catalog's names, so any exercise can be found in
// French one word at a time ("curl haltere incline assis").
export const WORD_SYNONYMS: Record<string, string[]> = {
  // Abbreviations / spellings
  db: ["dumbbell"],
  dumbell: ["dumbbell"],
  dumbel: ["dumbbell"],
  bb: ["barbell"],
  kb: ["kettlebell"],
  ez: ["ez"],
  tbar: ["t"],
  bw: ["bodyweight"],
  sa: ["single"],
  sl: ["single"],
  // Equipment
  haltere: ["dumbbell"],
  halteres: ["dumbbell"],
  barre: ["barbell", "bar"],
  barres: ["bar", "bars"],
  poulie: ["cable"],
  poulies: ["cable"],
  cables: ["cable"],
  cable: ["cable"],
  elastique: ["band"],
  elastiques: ["band"],
  bande: ["band"],
  corde: ["rope"],
  disque: ["plate"],
  disques: ["plate"],
  ballon: ["ball"],
  banc: ["bench"],
  bancs: ["benches"],
  machine: ["machine", "lever"],
  machines: ["machine", "lever"],
  kettlebells: ["kettlebell"],
  traineau: ["sled"],
  anneaux: ["ring"],
  anneau: ["ring"],
  serviette: ["towel"],
  mur: ["wall"],
  sol: ["floor"],
  marche: ["step", "walking", "march"],
  rouleau: ["roller", "roll"],
  roue: ["wheel"],
  sangle: ["suspension", "strap"],
  trx: ["suspension"],
  landmine: ["landmine"],
  // Positions
  assis: ["seated", "sit"],
  debout: ["standing"],
  allonge: ["lying"],
  couche: ["lying", "bench"],
  incline: ["incline"],
  inclinee: ["incline"],
  decline: ["decline"],
  declinee: ["decline"],
  penche: ["bent", "over"],
  genou: ["knee", "kneeling"],
  genoux: ["knee", "kneeling", "knees"],
  agenouille: ["kneeling"],
  ventre: ["prone"],
  dos: ["back", "supine"],
  cote: ["side", "lateral"],
  lateral: ["lateral", "side"],
  laterale: ["lateral", "side"],
  laterales: ["lateral", "side"],
  frontal: ["front"],
  frontale: ["front"],
  avant: ["front", "forward"],
  arriere: ["rear", "back", "reverse", "behind"],
  inverse: ["reverse"],
  inversee: ["reverse"],
  unilateral: ["single"],
  unilaterale: ["single"],
  alterne: ["alternating"],
  alternee: ["alternating"],
  alternes: ["alternating"],
  serre: ["close", "narrow"],
  serree: ["close", "narrow"],
  large: ["wide"],
  neutre: ["neutral"],
  supination: ["underhand", "supinated", "chin"],
  pronation: ["overhand", "pronated"],
  haut: ["high", "upper"],
  haute: ["high"],
  bas: ["low", "lower"],
  basse: ["low"],
  droit: ["straight", "right"],
  droite: ["straight", "right"],
  gauche: ["left"],
  tendu: ["straight", "stiff"],
  tendues: ["straight", "stiff"],
  croise: ["cross", "crossed"],
  surleve: ["elevated"],
  sureleve: ["elevated"],
  sureleves: ["elevated"],
  // Body parts
  pec: ["chest", "pec"],
  pecs: ["chest", "pec"],
  pectoral: ["chest"],
  pectoraux: ["chest"],
  poitrine: ["chest"],
  // "épaulé" (the clean) and "épaule" (shoulder) normalize the same.
  epaule: ["shoulder", "clean"],
  epaules: ["shoulder"],
  deltoide: ["delt"],
  deltoides: ["delt"],
  bras: ["arm", "arms"],
  avantbras: ["forearm"],
  poignet: ["wrist"],
  poignets: ["wrist"],
  main: ["hand"],
  mains: ["hands"],
  doigts: ["finger"],
  coude: ["elbow"],
  coudes: ["elbows"],
  cou: ["neck"],
  nuque: ["neck", "behind"],
  tete: ["head"],
  dorsaux: ["lat"],
  dorsal: ["lat"],
  lombaires: ["back", "hyperextension"],
  abdos: ["crunch", "ab"],
  abdominaux: ["crunch", "ab"],
  oblique: ["oblique"],
  obliques: ["oblique"],
  hanche: ["hip"],
  hanches: ["hip"],
  fessier: ["glute"],
  fessiers: ["glute"],
  fesses: ["glute"],
  cuisse: ["thigh", "leg"],
  cuisses: ["thigh", "leg"],
  quadriceps: ["quadriceps", "leg"],
  quads: ["quadriceps", "leg"],
  ischio: ["hamstring"],
  ischios: ["hamstring"],
  jambe: ["leg"],
  jambes: ["leg", "legs"],
  mollet: ["calf"],
  mollets: ["calf"],
  cheville: ["ankle"],
  chevilles: ["ankle"],
  pied: ["foot"],
  pieds: ["feet", "foot"],
  pointe: ["toe"],
  pointes: ["toe"],
  talon: ["heel"],
  talons: ["heels", "heel"],
  tronc: ["trunk", "torso"],
  buste: ["torso", "trunk"],
  trapeze: ["shrug", "trapezius"],
  trapezes: ["shrug", "trapezius"],
  biceps: ["biceps", "curl"],
  bicep: ["biceps", "curl"],
  triceps: ["triceps"],
  tricep: ["triceps"],
  // Movements
  developpe: ["press"],
  presse: ["press"],
  poussee: ["push", "press", "thrust"],
  pousser: ["push"],
  tirage: ["pulldown", "row", "pull"],
  tirer: ["pull"],
  traction: ["pull", "chin"],
  tractions: ["pull", "chin"],
  rowing: ["row"],
  rameur: ["row"],
  ecarte: ["fly"],
  ecartes: ["fly"],
  flys: ["fly"],
  flyes: ["fly"],
  flye: ["fly"],
  elevation: ["raise"],
  elevations: ["raise"],
  releve: ["raise"],
  leve: ["raise", "lift"],
  levee: ["raise", "lift"],
  flexion: ["curl", "bend", "flexion"],
  flexions: ["curl", "bend"],
  extensions: ["extension"],
  rotation: ["rotation", "twist"],
  rotations: ["rotation", "twist"],
  torsion: ["twist"],
  fente: ["lunge"],
  fentes: ["lunge"],
  pompe: ["push"],
  pompes: ["push"],
  gainage: ["plank"],
  planche: ["plank", "planche"],
  haussement: ["shrug"],
  haussements: ["shrug"],
  oiseau: ["reverse", "rear"],
  etirement: ["stretch"],
  etirements: ["stretch"],
  saut: ["jump"],
  sauts: ["jump"],
  saute: ["jump"],
  sauter: ["jump"],
  sautes: ["jump"],
  course: ["run", "running"],
  courir: ["run"],
  marcher: ["walking", "walk"],
  velo: ["bike", "cycle"],
  coup: ["kick", "punch"],
  maintien: ["hold"],
  tenue: ["hold"],
  porte: ["carry"],
  arrache: ["snatch"],
  jete: ["jerk"],
  balance: ["swing"],
  // More catalog words
  prise: ["grip"],
  prises: ["grip"],
  dessus: ["overhead", "over"],
  appui: ["supported", "support"],
  appuye: ["supported"],
  soutenu: ["supported"],
  support: ["support", "supported"],
  assiste: ["assisted"],
  assistee: ["assisted"],
  aide: ["assisted"],
  pupitre: ["preacher"],
  marteau: ["hammer"],
  leste: ["weighted"],
  lestee: ["weighted"],
  plat: ["flat"],
  partenaire: ["partner"],
  suspendu: ["hanging"],
  suspension: ["hanging", "suspension"],
  medecine: ["medicine"],
  pont: ["bridge"],
  concentre: ["concentration"],
  regroupe: ["tuck"],
  corps: ["body", "bodyweight"],
  deux: ["two", "double"],
  double: ["double", "dual"],
  parallele: ["parallel"],
  paralleles: ["parallel"],
  ecart: ["stance", "straddle"],
  chaise: ["chair"],
  toucher: ["touch"],
  touche: ["touch", "tap"],
  oppose: ["opposite"],
  opposee: ["opposite"],
  resistance: ["resisted"],
  roulade: ["rollout", "roll"],
  profond: ["deep"],
  profonde: ["deep"],
  roumain: ["romanian"],
  visage: ["face"],
  tendue: ["extended", "straight"],
  poignee: ["handle"],
  poignees: ["handle"],
  externe: ["external"],
  interne: ["internal"],
  exterieur: ["outward"],
  bassin: ["pelvic", "hip"],
  omoplate: ["scapular"],
  omoplates: ["scapular"],
  harnais: ["harness"],
  quatre: ["four"],
  pattes: ["four"],
  ancre: ["anchored"],
  vertical: ["vertical"],
  verticale: ["vertical"],
  horizontal: ["horizontal"],
  horizontale: ["horizontal"],
  ane: ["donkey"],
  complet: ["full"],
  complete: ["full"],
  pouce: ["thumb"],
  poirier: ["handstand"],
  diagonale: ["diagonal"],
  crochet: ["hook"],
  equilibre: ["balance"],
  stabilite: ["stability"],
  suisse: ["stability"],
  oscillant: ["swing"],
  explosif: ["explosive", "jump"],
  pliometrique: ["jump", "plyometric"],
  isometrique: ["hold"],
  statique: ["hold"],
  boite: ["box"],
  caisse: ["box"],
  pneu: ["tire"],
  masse: ["sledgehammer"],
  // Plurals / variants of catalog words
  squats: ["squat"],
  curls: ["curl"],
  rows: ["row"],
  presses: ["press"],
  raises: ["raise"],
  lunges: ["lunge"],
  deadlifts: ["deadlift"],
  dips: ["dip"],
  shrugs: ["shrug"],
  crunches: ["crunch"],
  pullups: ["pull"],
  chinups: ["chin"],
  pushups: ["push"],
  situps: ["sit"],
  kickbacks: ["kickback"],
  pushdowns: ["pushdown"],
  pulldowns: ["pulldown"],
  hamstrings: ["hamstring"],
  glutes: ["glute"],
  calves: ["calf"],
  delts: ["delt"],
  lats: ["lat"],
  traps: ["shrug"],
  quad: ["quadriceps"],
  abs: ["ab", "crunch"],
  tri: ["triceps"],
  bi: ["biceps"],
};

// Nicknames attached to every exercise whose name matches `match`
// (patterns, not ids, so they also apply to custom exercises and survive
// catalog renames).
export const ALIAS_RULES: { match: RegExp; aliases: string[] }[] = [
  // Chest
  {
    match: /machine.*chest fly|pec deck/i,
    aliases: ["pec deck", "pec dec", "peck deck", "pec fly", "pecfly", "butterfly", "papillon", "ecarte machine", "fly machine", "machine fly"],
  },
  {
    match: /machine.*reverse fly|reverse.*pec deck/i,
    aliases: ["reverse pec deck", "reverse butterfly", "oiseau machine", "rear delt machine", "rear delt fly"],
  },
  { match: /cable.*fly|crossover/i, aliases: ["cable crossover", "vis a vis", "poulie vis a vis", "ecarte poulie", "cable fly", "cable flye"] },
  { match: /dumbbell.*fly/i, aliases: ["ecarte halteres", "ecarte couche", "dumbbell flye", "chest fly"] },
  { match: /bench press/i, aliases: ["developpe couche", "dc", "bench", "flat bench"] },
  { match: /incline.*press/i, aliases: ["developpe incline", "incline bench"] },
  { match: /decline.*press/i, aliases: ["developpe decline", "decline bench"] },
  { match: /machine.*chest press|chest press/i, aliases: ["developpe machine", "presse pectorale", "presse pectoraux", "chest press"] },
  { match: /push-up/i, aliases: ["pompe", "pompes", "pushup", "press up"] },
  { match: /\bdip\b/i, aliases: ["dips", "dip", "barres paralleles"] },
  { match: /pullover/i, aliases: ["pull over", "pullover"] },
  // Back
  { match: /^(?!.*straight-arm).*pulldown/i, aliases: ["tirage vertical", "tirage poitrine", "lat pull down", "pulldown", "lat pull"] },
  { match: /straight-arm pulldown/i, aliases: ["pullover poulie", "straight arm pulldown"] },
  { match: /seated.*(cable|machine).*row|cable.*seated.*row|low.*row/i, aliases: ["tirage horizontal", "rowing assis", "seated row", "low row", "tirage assis", "cable row"] },
  { match: /t-bar row/i, aliases: ["rowing t", "t bar row", "tbar row", "rowing t bar"] },
  { match: /bent-over.*row|barbell.*row|pendlay/i, aliases: ["rowing barre", "rowing buste penche", "rowing penche", "barbell row", "bent over row"] },
  { match: /dumbbell.*row/i, aliases: ["rowing haltere", "rowing unilateral", "one arm row", "db row", "kroc row"] },
  { match: /upright row/i, aliases: ["tirage menton", "rowing menton"] },
  { match: /pull-up/i, aliases: ["traction", "tractions", "pullup", "traction pronation"] },
  { match: /chin-up/i, aliases: ["traction supination", "tractions supination", "chinup", "chin"] },
  { match: /hyperextension|back extension/i, aliases: ["lombaires", "extension lombaire", "hyperextension", "back extension", "superman"] },
  { match: /good morning/i, aliases: ["good morning", "bonjour"] },
  // Shoulders
  { match: /overhead press|shoulder press|military press/i, aliases: ["developpe militaire", "developpe epaules", "developpe nuque", "presse a epaules", "ohp", "military press", "shoulder press"] },
  { match: /arnold/i, aliases: ["developpe arnold", "arnold press"] },
  { match: /push press/i, aliases: ["presse en poussee"] },
  { match: /lateral raise/i, aliases: ["elevation laterale", "elevations laterales", "lat raise", "side raise", "shoulder fly", "lateral fly"] },
  { match: /front raise/i, aliases: ["elevation frontale", "elevations frontales"] },
  { match: /reverse fly|rear.delt/i, aliases: ["oiseau", "rear delt", "rear delt fly", "arriere d epaule", "deltoide posterieur"] },
  { match: /face pull/i, aliases: ["face pull", "tirage visage"] },
  { match: /shrug/i, aliases: ["haussement d epaules", "haussements d epaules", "shrugs", "trapezes"] },
  { match: /external rotation|internal rotation|rotator/i, aliases: ["rotation externe", "rotation interne", "coiffe des rotateurs"] },
  // Arms
  { match: /pushdown/i, aliases: ["extension triceps poulie", "triceps poulie", "push down", "pushdown", "tricep rope", "rope pushdown"] },
  { match: /skull crusher|lying.*triceps extension/i, aliases: ["barre au front", "skull crusher", "skullcrusher", "extension triceps allonge", "french press", "french extension", "nose breaker"] },
  { match: /overhead.*triceps extension|triceps.*overhead/i, aliases: ["extension triceps nuque", "extension verticale", "french press", "french curl", "overhead extension"] },
  { match: /kickback/i, aliases: ["kickback", "extension triceps penche", "kick back"] },
  { match: /close-grip.*bench press/i, aliases: ["developpe couche prise serree", "close grip bench", "cgbp"] },
  { match: /preacher/i, aliases: ["curl pupitre", "pupitre", "larry scott", "preacher curl"] },
  { match: /hammer curl/i, aliases: ["curl marteau", "hammer curl"] },
  { match: /concentration curl/i, aliases: ["curl concentre", "curl concentration"] },
  { match: /spider curl/i, aliases: ["curl araignee"] },
  { match: /reverse curl/i, aliases: ["curl inverse", "curl pronation"] },
  { match: /zottman/i, aliases: ["curl zottman"] },
  { match: /wrist curl|wrist extension/i, aliases: ["curl poignet", "flexion poignets", "avant bras"] },
  { match: /biceps curl|barbell curl|dumbbell curl|cable curl|ez.*curl/i, aliases: ["curl biceps", "bicep curl", "biceps"] },
  // Legs
  { match: /leg press|sled.*press/i, aliases: ["presse", "presse a cuisses", "presse jambes", "presse inclinee", "presse 45"] },
  { match: /leg extension/i, aliases: ["leg extension", "extension jambes", "extension quadriceps", "leg ext", "quad extension"] },
  { match: /leg curl/i, aliases: ["leg curl", "ischios machine", "curl ischios", "hamstring curl", "curl jambes"] },
  { match: /hack squat/i, aliases: ["hack", "hack squat", "squat hackenberg"] },
  { match: /split squat|rear-foot/i, aliases: ["squat bulgare", "fente bulgare", "bulgarian split squat", "bulgarian"] },
  { match: /front squat/i, aliases: ["squat avant"] },
  { match: /goblet squat/i, aliases: ["squat gobelet", "goblet"] },
  { match: /sumo/i, aliases: ["sumo"] },
  { match: /romanian deadlift/i, aliases: ["rdl", "souleve de terre roumain", "sdt roumain"] },
  { match: /stiff.?leg.*deadlift/i, aliases: ["souleve de terre jambes tendues", "sldl", "stiff leg"] },
  { match: /deadlift/i, aliases: ["souleve de terre", "sdt", "deadlift"] },
  { match: /trap bar/i, aliases: ["barre hexagonale", "hex bar"] },
  { match: /hip thrust|glute bridge/i, aliases: ["hip thrust", "pont fessier", "releve de bassin", "poussee des hanches"] },
  { match: /calf raise|calf press/i, aliases: ["mollets", "extension mollets", "lever de mollets", "calf raise"] },
  { match: /hip abduction/i, aliases: ["abducteurs", "machine abducteurs", "abductor", "hip abductor"] },
  { match: /hip adduction/i, aliases: ["adducteurs", "machine adducteurs", "adductor", "hip adductor"] },
  { match: /lunge/i, aliases: ["fente", "fentes"] },
  { match: /step-up|step up/i, aliases: ["montee sur banc", "step up"] },
  { match: /nordic/i, aliases: ["nordic curl", "nordic ham curl"] },
  { match: /glute.ham/i, aliases: ["ghr", "glute ham raise"] },
  { match: /kickback|donkey kick/i, aliases: ["kickback fessier", "glute kickback"] },
  { match: /wall sit/i, aliases: ["chaise", "chaise contre le mur"] },
  // Core
  { match: /plank/i, aliases: ["gainage", "planche"] },
  { match: /crunch/i, aliases: ["abdos", "crunch"] },
  { match: /sit-up/i, aliases: ["releve de buste", "abdos", "situp"] },
  { match: /leg raise|knee raise/i, aliases: ["releve de jambes", "releve de genoux", "abdos suspendu"] },
  { match: /captains/i, aliases: ["chaise romaine", "captain chair"] },
  { match: /russian twist/i, aliases: ["rotation russe", "russian twist"] },
  { match: /rollout|ab wheel/i, aliases: ["roue abdominale", "ab wheel", "roulette"] },
  { match: /mountain climber/i, aliases: ["grimpeur", "grimpeurs"] },
  { match: /dead bug/i, aliases: ["dead bug", "deadbug"] },
  { match: /bird dog/i, aliases: ["bird dog", "chien d arret"] },
  { match: /pallof/i, aliases: ["pallof press", "anti rotation"] },
  { match: /windmill/i, aliases: ["moulin a vent"] },
  // Olympic / full body / cardio
  { match: /\bclean\b/i, aliases: ["epaule", "power clean"] },
  { match: /snatch/i, aliases: ["arrache"] },
  { match: /jerk/i, aliases: ["epaule jete", "jete"] },
  { match: /swing/i, aliases: ["kettlebell swing", "swing"] },
  { match: /farmer|carry/i, aliases: ["marche du fermier", "farmer walk", "farmer carry"] },
  { match: /burpee/i, aliases: ["burpees"] },
  { match: /jumping jack/i, aliases: ["jumping jacks"] },
  { match: /jump rope/i, aliases: ["corde a sauter", "saut a la corde"] },
  { match: /high knee/i, aliases: ["montee de genoux", "montees de genoux"] },
  { match: /butt kick/i, aliases: ["talons fesses"] },
  { match: /battle rope|battling rope/i, aliases: ["corde ondulatoire", "battle rope"] },
  { match: /box jump/i, aliases: ["saut sur boite", "box jump"] },
  { match: /treadmill|run/i, aliases: ["course", "tapis de course"] },
  { match: /elliptical/i, aliases: ["velo elliptique", "elliptique"] },
  { match: /stationary bike|cycling|air bike/i, aliases: ["velo", "velo stationnaire"] },
  { match: /stretch/i, aliases: ["etirement", "stretching"] },
  { match: /foam roll/i, aliases: ["rouleau", "rouleau de massage", "foam roller"] },
  { match: /smith/i, aliases: ["smith machine", "cadre guide", "barre guidee"] },
];
